name: Golang Docker Build

on:
  push:
    branches:
      - "**" # Trigger on push to any branch
env:
  CONTAINER_REPOSITORY: quay.io/judithhershko1/ # PUT YOUR OWN USERNAME HERE
  CONTAINER_IMAGE: redhat_test
  GOLANG_VERSION: 1.23

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Quay.io login
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: judithhershko1+judithhershko_robot
          password: ${{ secrets.PASSWORD_1 }}

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: quay.io/judithhershko1/redhat_test

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
